### ISSUE TITLE
Module doesn't work (installed using Chocolatey)

### ISSUE THREAD

**Issue by ferenczy** [mmanela/PsVso#2]
I have installed `VsVso` using Chocolatey. It didn't print any error during the installation. Module directory `VsVso` in a directory `c:\users\ferenczy\Documents\WindowsPowerShell\Modules\` looks good. Environment variable `PSModulePath` contains this module directory. But nothing from `VsVso` works actually. `Get-help VsVso`  doesn't find anything, any cmdlet from `VsVso` doesn't work.

`Get-Module -ListAvailable` prints this:

    $ Get-Module -ListAvailable

        Directory: C:\Users\ferenczy\Documents\WindowsPowerShell\Modules

    ModuleType Version    Name                                ExportedCommands
    ---------- -------    ----                                ----------------
    Script     0.5.0      PsVso                               {Push-ToVso, ...

So it seems the module is not loaded, even if PowerShell knows about it.

What can be wrong?

**Comment by mmanela** [comment]
What happens when you try to run a command like Get-BuildStatus?

**Comment by ferenczy** [comment]
It's not defined at all (any of PsVso's commands), so I'm getting this:

```
[2015-09-10 12:05.07] ferenczy@ferenczy-dell C:\Users\ferenczy
$ Get-BuildStatus
Get-BuildStatus : The term 'Get-BuildStatus' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-BuildStatus
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-BuildStatus:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by mmanela** [comment]
Did you try to run Import-Module PsVso?

**Comment by ferenczy** [comment]
Yep, that works, the point is that it's not loaded automatically as you describe in the readme:

> Install PsVso

> `choco install PsVso`
> Once installed all the cmdlets should be auto-loaded and ready to use.

So should I add the `Import-Module` command into my PowerShell's profile to load it explicitly?

**Comment by mmanela** [comment]
Odd, well I updated the main page to reflect this. Thanks

**Comment by ferenczy** [comment]
So does it mean that it works without explicitly importing it in your case?

How does an output of `Get-Module -ListAvailable` look in your case (just a part related to PsVso module as I posted in my first comment)?
